#!/bin/sh
#
# Author: Garry Dolley
# Date: 05-12-2014
#
# Copyright ⓒ 2014 ARP Networks, Inc.
#
# A runit "run" script for abuse_mail_monitor.rb

# Modify INSTALL_DIR as needed
INSTALL_DIR=/root/tools/

exec 2>&1
exec ruby $INSTALL_DIR/abuse_mail_monitor.rb
